[package]
name = "papper-document"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
regex.workspace = true
roxmltree.workspace = true
html-escape.workspace = true
zip.workspace = true
papper-core.workspace = true
papper-platform.workspace = true
resvg.workspace = true
base64.workspace = true
flate2.workspace = true
percent-encoding.workspace = true
mime_guess.workspace = true
sha2.workspace = true
tempfile.workspace = true
encoding_rs = "0.8"
