"""
Pandoc filter to adjust Table and Figure.

1. Support two column layout for Table and Figure with attribute `twocol=true`
2. Remove autogenerated "Figure " or "Table " prefix from caption
3. Using table instead of longtable (default in Pandoc) for Table, which is not supported in double-column layout. AI conversion is not used.
"""

import os
import sys
from typing import Optional, cast
import panflute as pf
from dotenv import load_dotenv

load_dotenv()

LOG_LEVELS = {"DEBUG": 10, "INFO": 20, "WARNING": 30, "WARN": 30, "ERROR": 40}


def should_log(level: str) -> bool:
    """Return True when this Pandoc filter should emit a log message."""
    configured = os.getenv("PANDOC_TEMPLATE_LOG_LEVEL", "INFO").strip().upper()
    return LOG_LEVELS.get(level, 30) >= LOG_LEVELS.get(configured, 30)


def log_info(message: str) -> None:
    """Emit filter progress only when INFO logging is enabled."""
    if should_log("INFO"):
        print(message, file=sys.stderr)


def log_debug(message: str) -> None:
    """Emit verbose filter progress only when DEBUG logging is enabled."""
    if should_log("DEBUG"):
        print(message, file=sys.stderr)


def log_warning(message: str) -> None:
    """Emit a filter warning; warnings remain visible by default."""
    if should_log("WARNING"):
        print(message, file=sys.stderr)

try:
# pyright: reportPossiblyUnboundVariable=false
    from google import genai
    from google.genai import types
    from google.genai.types import ContentUnionDict
except ImportError:
    print("Error: google-genai package not installed.", file=sys.stderr)
    print("Install it with: pip install google-genai", file=sys.stderr)


# Initialize Gemini API
API_KEY = os.getenv("GEMINI_API_KEY")
if not API_KEY:
    log_warning("Warning: GEMINI_API_KEY environment variable not set.")
    log_info("Tables will be converted with fallback conversion.")
    GEMINI_AVAILABLE = False
    GEMINI_CLIENT = None
else:
    # Set up proxy for HTTP requests
    os.environ['HTTP_PROXY'] = 'http://127.0.0.1:7890'
    os.environ['HTTPS_PROXY'] = 'http://127.0.0.1:7890'
    
    # Initialize Gemini client
    try:
        GEMINI_CLIENT = genai.Client(api_key=API_KEY)
        GEMINI_AVAILABLE = True
    except Exception as e:
        print(f"Error initializing Gemini client: {str(e)}", file=sys.stderr)
        GEMINI_AVAILABLE = False
        GEMINI_CLIENT = None


# Reference LaTeX table styles for the AI model
LATEX_STYLE_EXAMPLES = """
Example 1 (Simple table with header row):
\\begin{table}[htbp]
\\centering
\\caption{Performance comparison}
\\label{tbl:performance}
\\begin{tabular}{lcccc}
\\hline
\\textbf{Model} & \\textbf{Accuracy} & \\textbf{Speed} & \\textbf{Size} \\\\
\\hline
Model A & 92.3 & 35 & 310 \\\\
Model B & 87.7 & 28 & 1300 \\\\
Model C & 86.6 & 33 & 325 \\\\
\\hline
\\end{tabular}
\\end{table}

Example 2 (Table with alignment and complex content):
\\begin{table*}[t]
\\centering
\\caption{Ablation study results}
\\label{tbl:ablation}
\\begin{tabular}{lccccc}
\\hline
\\textbf{Configuration} & \\textbf{KD} & \\textbf{Quant} & \\textbf{Acc (\\%)} & \\textbf{mAP (\\%)} \\\\
\\hline
Baseline & No & No & 84.2 & 80.6 \\\\
+ Feature KD & Yes & No & 87.7 & 86.0 \\\\
+ Adaptive Quant & Yes & Yes & 89.3 & 87.6 \\\\
\\textbf{Full Method} & Yes & Yes & \\textbf{92.3} & \\textbf{90.4} \\\\
\\hline
\\end{tabular}
\\end{table*}

Example 3 (Table with images):
\\begin{table}[htbp]
\\centering
\\caption{Qualitative results}
\\label{tbl:qualitative}
\\begin{tabular}{ccc}
\\hline
\\textbf{Sample} & \\textbf{Description} & \\textbf{Category} \\\\
\\hline
\\includegraphics[width=0.15\\linewidth]{images/results/1.jpg} & Road collapse detected & Road Collapse \\\\
\\includegraphics[width=0.15\\linewidth]{images/results/2.jpg} & Major landslide & Landslide \\\\
\\hline
\\end{tabular}
\\end{table}
"""

CONVERSION_PROMPT = """You are a LaTeX table formatting expert. Convert the following Pandoc standard Markdown table to a well-formatted LaTeX table.

Requirements:
1. Use \\begin{table}[htbp] or \\begin{table*}[t] (use table* for wide tables that need full page width in double-column layout)
2. Include \\centering before the tabular environment
3. Add \\caption{...} with the provided caption
4. Add \\label{...} with the provided label (or generate one from caption if not provided)
5. Use \\hline for horizontal lines
6. Make header rows bold with \\textbf{...}
7. Choose appropriate column alignment (l=left, c=center, r=right) based on content
8. For numeric columns, use right or center alignment
9. For text columns, use left alignment
10. Handle special LaTeX characters properly (escape _, %, &, etc.)
11. For images in tables, use \\includegraphics[width=X\\linewidth]{path}
12. Keep the LaTeX clean and properly indented
13. Use regular tabular (not longtable, not tabularray)
14. For Yes/No or checkmarks, consider using symbols like \\checkmark or simple text
15. Make emphasized content bold using \\textbf{...}
16. Convert **bold** text to \\textbf{{bold}}
17. Convert *italic* text to \\textit{{italic}}
18. Convert `code` to \\texttt{{code}}
19. Convert $math$ to $math$ (keep as is)
20. Convert ![alt](path){width=X%} to \\includegraphics[width=X\\linewidth]{{path}}

Reference style examples:
{style_examples}

Example of Pandoc Markdown table format:
| **Header 1**        | **Header 2**         |
|:--------------------|:--------------------:|
| Value 1             | Value 2              |
| Value 3             | Value 4              |
| Value 5             | Value 6              |

: Table caption text {#tbl:example}

Input Pandoc Markdown table:
{markdown_table}

Now generate ONLY the LaTeX table code (from \\begin{{table}} to \\end{{table}}). Do not include any explanations or markdown code blocks.
"""


def extract_text_from_inlines(inlines) -> str:
    """Extract plain text from panflute inline elements."""
    if not inlines:
        return ""
    
    result = []
    for elem in inlines:
        if isinstance(elem, pf.Str):
            # Escape special LaTeX characters
            text = elem.text
            text = text.replace('\\', '\\textbackslash{}')
            text = text.replace('_', '\\_')
            text = text.replace('%', '\\%')
            text = text.replace('$', '\\$')
            text = text.replace('#', '\\#')
            text = text.replace('&', '\\&')
            text = text.replace('{', '\\{')
            text = text.replace('}', '\\}')
            result.append(text)
        elif isinstance(elem, pf.Space):
            result.append(' ')
        elif isinstance(elem, pf.Quoted):
            inner = extract_text_from_inlines(elem.content)
            result.append(f"\"{inner}\"")
        elif isinstance(elem, pf.Strong):
            # Handle bold text
            inner = extract_text_from_inlines(elem.content)
            result.append(f"\\textbf{{{inner}}}")
        elif isinstance(elem, pf.Emph):
            # Handle italic text
            inner = extract_text_from_inlines(elem.content)
            result.append(f"\\textit{{{inner}}}")
        elif isinstance(elem, pf.Code):
            result.append(f"\\texttt{{{elem.text}}}")
        elif isinstance(elem, pf.Math):
            if elem.format == "InlineMath":
                result.append(f"${elem.text}$")
            else:
                result.append(f"$${elem.text}$$")
        elif isinstance(elem, pf.Image):
            # Handle images in table cells
            # width = elem.attributes.get('width', '15%')
            # # Convert percentage to linewidth fraction
            # if '%' in width:
            #     fraction = float(width.replace('%', '')) / 100
            #     width_spec = f"{fraction:.2f}\\linewidth"
            # else:
            #     width_spec = width
            # result.append(f"\\includegraphics[width={width_spec}]{{{elem.url}}}")
            
            # 对于表格中的图片，我们在 extract_table_info 函数中使用了 m{2.8cm} 
            # 来解决图片列垂直居中的问题，而这会导致 \\linewidth 指向的是单元格的宽度
            # 而不是页面行的宽度，因此需要将宽度固定为 0.95\\linewidth
            result.append(f"\\includegraphics[width=0.95\\linewidth]{{{elem.url}}}")
        elif isinstance(elem, pf.RawInline):
            if elem.format == 'latex':
                result.append(elem.text)
        else:
            # Fallback: stringify
            pf.debug(f"Fallback: stringify {elem}")
            result.append(pf.stringify(elem))
    
    return ''.join(result)


def extract_table_info(table: pf.Table) -> dict:
    """Extract structured information from a panflute Table element."""
    info = {
        'caption': '',
        'label': '',
        'headers': [],
        'alignment': [],
        'rows': [],
        'attrs': {}
    }
    
    info['attrs'] = table.attributes
    
    if table.caption:
        caption_text = pf.stringify(table.caption)
        info['caption'] = caption_text
        
    if table.identifier:
        info['label'] = table.identifier
    
    if table.colspec:
        for align, _ in table.colspec:
            if align == 'AlignLeft':
                info['alignment'].append('l')
            elif align == 'AlignRight':
                info['alignment'].append('r')
            elif align == 'AlignCenter':
                info['alignment'].append('c')
            else:
                info['alignment'].append('l')  # default
            
    
    # Extract headers from table head
    if table.head and table.head.content:
        for row in table.head.content:
            if hasattr(row, 'content'):
                header_row = []
                for cell in row.content:
                    if hasattr(cell, 'content'):
                        cell_content = []
                        for block in cell.content:
                            if isinstance(block, pf.Para) or isinstance(block, pf.Plain):
                                cell_content.append(extract_text_from_inlines(block.content))
                        header_row.append(' '.join(cell_content))
                if header_row:
                    info['headers'] = header_row
                    break  # Only take first header row
    
    # Extract data rows from table body
    if hasattr(table, 'content'):
        for body in table.content:
            if hasattr(body, 'content'):
                for row in body.content:
                    if hasattr(row, 'content'):
                        data_row = []
                        for cell in row.content:
                            if hasattr(cell, 'content'):
                                cell_content = []
                                for block in cell.content:
                                    if isinstance(block, pf.Para) or isinstance(block, pf.Plain):
                                        cell_content.append(extract_text_from_inlines(block.content))
                                data_row.append(' '.join(cell_content))
                        if data_row:
                            info['rows'].append(data_row)
    
    # 对于包含图片列的表格，图片所在的行中，其他列的文字会无法垂直居中
    # m{2.8cm} 可以解决这个问题
    # 参考 https://blog.csdn.net/happy_demo/article/details/105430091
    for i in range(len(info['alignment'])):
        if any('\\includegraphics' in row[i] for row in info['rows']):
            info['alignment'][i] = 'm{2.8cm}'
            
    return info


def convert_table_with_ai(markdown_table: str) -> Optional[str]:
    """Use Gemini AI to convert table information to LaTeX."""
    if not GEMINI_AVAILABLE or GEMINI_CLIENT is None:
        return None
    
    try:
        prompt = CONVERSION_PROMPT.replace(
            '{style_examples}', LATEX_STYLE_EXAMPLES,
        ).replace(
            '{markdown_table}', markdown_table
        )
        
        # Prepare content for the new API
        contents: list[ContentUnionDict] = [
            types.Content( 
                role="user",
                parts=[
                    types.Part.from_text(text=prompt),
                ],
            ),
        ]
        
        # Configure generation
        generate_content_config = types.GenerateContentConfig(
            temperature=0.3,  # Lower temperature for more consistent formatting
            max_output_tokens=4096,
            thinking_config=types.ThinkingConfig(
                thinking_budget=0,
            ),
            http_options=types.HttpOptions(
                retry_options=types.HttpRetryOptions(
                    attempts=3
                ),
            ),
        )
        
        # Call Gemini API using the new client
        model = "gemini-flash-latest"
        response_chunks = []
        
        for chunk in GEMINI_CLIENT.models.generate_content_stream(
            model=model,
            contents=contents,
            config=generate_content_config,
        ):
            if chunk.text:
                response_chunks.append(chunk.text)
        # print cached token
        if chunk and chunk.usage_metadata:  # pyright: ignore[reportPossiblyUnboundVariable]
            pf.debug(f"Cached token: {chunk.usage_metadata.cached_content_token_count}")
        
        # Combine all chunks
        latex_code = ''.join(response_chunks).strip()
        
        # Clean up the response (remove markdown code blocks if present)
        if latex_code.startswith('```'):
            lines = latex_code.split('\n')
            latex_code = '\n'.join(lines[1:-1] if len(lines) > 2 else lines)
        
        # Remove any remaining markdown artifacts
        latex_code = latex_code.replace('```latex', '').replace('```', '').strip()
        
        pf.debug("Successfully converted table with AI")
        return latex_code
        
    except Exception as e:
        pf.debug(f"Error converting table with AI: {str(e)}")
        return None


def fallback_table_conversion(table_info: dict) -> str:
    """Fallback: Generate basic LaTeX table if AI conversion fails."""
    caption = table_info['caption']
    label = table_info['label']
    headers = table_info['headers']
    alignment = table_info['alignment'] if table_info['alignment'] else ['l'] * len(headers)
    rows = table_info['rows']
    
    # Determine if we need table* (wide table)
    num_cols = len(headers)
    table_env = 'table*' if num_cols > 5 or 'includegraphics' in rows.__str__() else 'table'
    if 'twocol' in table_info['attrs']:
        table_env = 'table' if table_info['attrs']['twocol'] == 'false' else 'table*'
    
    # Build LaTeX
    latex_lines = [
        f"\\begin{{{table_env}}}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{(' '.join(alignment))}}}",
        "\\toprule",
    ]
    
    # Add headers
    if headers:
        header_line = ' & '.join([f"\\textbf{{{h}}}" for h in headers])
        latex_lines.append(header_line + " \\\\")
        latex_lines.append("\\midrule")
    
    # Add rows
    for row in rows:
        row_line = ' & '.join(row)
        latex_lines.append(row_line + " \\\\")
    
    latex_lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        f"\\end{{{table_env}}}"
    ])
    
    return '\n'.join(latex_lines)


def action(elem: pf.Element, doc: pf.Doc) -> Optional[pf.Element]:
    """
    Panflute action function to process each element.
    
    Args:
        elem: The element to process
        doc: The document
    
    Returns:
        Modified element or None
    """
    # Only process tables when outputting to LaTeX
    if 'debugpy' not in sys.modules and doc.format != 'latex':
        return None
    
    if isinstance(elem, pf.Caption) and (pf.stringify(elem).startswith('Figure ') or pf.stringify(elem).startswith('Table ')):
        elem.content.list[0].content = elem.content.list[0].content[4:]

    if isinstance(elem, pf.Figure):
        image_elem = elem.content.list[0].content.list[0]
        latex = cast(str, pf.convert_text(elem, input_format='panflute', output_format='latex'))
        if 'twocol' in image_elem.attributes and image_elem.attributes['twocol'] == 'true':
            # 双栏展示图片
            latex = latex.replace('{figure}', '{figure*}')
        else:
            # Latex 中在双栏模式下， \\textwidth 为单栏的宽度
            # 因此对于所有不双栏展示的图片，宽度都设置为 95%，否则图片会很小
            image_elem.attributes['width'] = '95%'
            return None
        return pf.RawBlock(latex, format='latex')
        
    if isinstance(elem, pf.Table):
        latex_code = None
        table_info = extract_table_info(elem)
        
        if not table_info['headers'] and not table_info['rows']:
            log_warning("Warning: Empty table found, skipping.")
            return None
        
        # Try AI conversion first
        # markdown_table: str = cast(str, pf.convert_text(elem, input_format='panflute', output_format='markdown'))
        # latex_code = convert_table_with_ai(markdown_table)
        
        # Fallback to basic conversion if AI fails
        if latex_code is None:
            # print("Using fallback table conversion...", file=sys.stderr)
            latex_code = fallback_table_conversion(table_info)
        
        # Return as RawBlock
        return pf.RawBlock(latex_code, format='latex')
    
    return None


def prepare(doc: pf.Doc) -> None:
    if doc.format == 'latex':
        log_debug("Table conversion filter initialized.")
        if not GEMINI_AVAILABLE:
            log_warning("WARNING: Gemini API not available. Using fallback conversion.")


def finalize(doc: pf.Doc) -> None:
    pass


def main(doc: pf.Doc | None = None):
    return pf.run_filter(
        action,
        prepare=prepare,
        finalize=finalize,
        doc=doc
    )


if __name__ == '__main__':
    if 'debugpy' in sys.modules:
        pf.debug('DEBUG MODE')
        sys.stdin = open('temp.json', 'r')
    main()
